version: '3.8'

services:
  mysql:
    image: mysql:8.1.0
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_LOCAL_PORT:-3316}:${MYSQL_DOCKER_PORT:-3306}"
    networks:
      - spring-mysql
    volumes:
      - db-data:/var/lib/mysql

  app:
    depends_on:
      - mysql
    image: optic-okulist
    restart: always
    build: .
    ports:
      - "${SPRING_LOCAL_PORT:-8088}:${SPRING_DOCKER_PORT:-8080}"
      - "${DEBUG_PORT:-5005}:5005"
    environment:
      SPRING_APPLICATION_JSON: >-
        {
          "spring.datasource.url": "jdbc:mysql://mysql:${MYSQL_DOCKER_PORT:-3306}/${MYSQL_DATABASE}?serverTimeZone=UTC",
          "spring.datasource.username": "${MYSQLDB_USER}",
          "spring.datasource.password": "${MYSQL_ROOT_PASSWORD}",
          "spring.jpa.hibernate.ddl-auto": "validate"
        }
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

    networks:
      - spring-mysql

volumes:
  db-data:

networks:
  spring-mysql:
